/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'root' at '17/05/27 0:31' with Gradle 2.14.1
 *
 * @author root, @date 17/05/27 0:31
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
